[package]
name = "kairoi"
version = "0.1.0"
edition = "2024"

[dev-dependencies]
tokio = { version = "1.47.1", features = ["full"] }

[dependencies]
crossbeam-channel = "0.5.15"
lazy_static = "1.5.0"
tokio = { version = "1.47.1", features = ["time", "rt"] }
